DenuncieSpam/Controllers/ReclamacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DenuncieSpam.Models;
using DenuncieSpam.AcessoDados.Interfaces;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using DenuncieSpam.Helpers;

namespace DenuncieSpam.Controllers
{
    
    //[IsAutenticatedAtributte]
    [Authorize (Roles ="Administrador, Usuario")]    
    public class ReclamacoesController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly IReclamacaoRepositorio _reclamacaoRepositorio;
        private readonly ILogger<ReclamacoesController> _logger;


        public ReclamacoesController(IUsuarioRepositorio usuarioRepositorio, IReclamacaoRepositorio reclamacaoRepositorio, ILogger<ReclamacoesController> logger)
        {
            
            _usuarioRepositorio = usuarioRepositorio;
            _reclamacaoRepositorio = reclamacaoRepositorio;
            _logger = logger;

            var usuario = _usuarioRepositorio.PegarUsuarioLogado(User);
            if (usuario == null)
            {                
                RedirectToAction("Login", "Usuarios");
            }            
        }

        
        
        // GET: Reclamacoes        
        public async Task<IActionResult> Index()
        {
            var usuario = await _usuarioRepositorio.PegarUsuarioLogado(User);
            if(usuario != null)
            {
                if(User.IsInRole("Usuario"))
                    return View(await _reclamacaoRepositorio.PegarTodosPorUsuario(usuario.Id));
            }

            var rec = await _reclamacaoRepositorio.PegarTodos();
            //_logger.LogInformation("Listando todos os registros");
            return View( rec );
        }


        // GET: Reclamacoes/Create
        public async Task<IActionResult> Create()
        {
            _logger.LogInformation("Nova Reclamacao");
            
            return  View();
        }

        // POST: Reclamacoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdReclamacao,Data,Empresa,Telefone,Email,Descricao,IdUsuario")] Reclamacao reclamacao)
        {
            var usuario = await _usuarioRepositorio.PegarUsuarioLogado(User);
            if (ModelState.IsValid && usuario != null)
            {                
                reclamacao.IdUsuario = usuario.Id;
                await _reclamacaoRepositorio.Inserir(reclamacao);
                _logger.LogInformation("Nova Reclamacao cadastrada");
                return RedirectToAction("Index", "Usuarios");
            }

            _logger.LogError("Erro no cadastro de reclamacao");
            return View(reclamacao);
        }

        // GET: Reclamacoes/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

            _logger.LogInformation("Atualizando Reclamacao");            
            
            var reclamacao =  await _reclamacaoRepositorio.PegarPeloId(id);

            if (reclamacao == null)
            {
                return NotFound();
            }
         
            return View(reclamacao);
            
        }

        // POST: Reclamacoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdReclamacao,Data,Empresa,Telefone,Email,Descricao,IdUsuario")] Reclamacao reclamacao)
        {
            var usuario = await _usuarioRepositorio.PegarUsuarioLogado(User);

            if (id != reclamacao.IdReclamacao && reclamacao.IdUsuario != usuario.Id)
            {
                _logger.LogError("Reclamação não encontrada");
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _reclamacaoRepositorio.Atualizar(reclamacao);
                _logger.LogInformation("Endereço atualizado");
                return RedirectToAction("Index", "Usuarios");
            }

            _logger.LogError("Reclamação não encontrada");
            return View(reclamacao);
        }
        

        // POST: Reclamacoes/Delete/5
        [HttpPost]        
        public async Task<IActionResult> Delete(int id)
        {
            var usuario = await _usuarioRepositorio.PegarUsuarioLogado(User);

            var reclamacao = await _reclamacaoRepositorio.PegarPeloId(id);

            if(usuario.Id != reclamacao.IdUsuario && !User.IsInRole("Administrador"))
            {
                return RedirectToAction("Index");
            }

            await _reclamacaoRepositorio.Excluir(id);
            //return Json("Reclamação excluída");
            _logger.LogInformation("Reclamação excluída");
            return RedirectToAction("Index");
        }

    }
}

DenuncieSpam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />    
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CooperaCity</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://bootswatch.com/4/cosmo/bootstrap.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://bootswatch.com/4/cosmo/bootstrap.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.min.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <div class="container">
            <a class="navbar-brand text-white" asp-controller="Home" asp-action="Index"><i class="fas fa-plus-square fa-lg"></i> CooperaCity</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link navbar-text text-white" asp-action="Index" asp-controller="Home">Início</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link navbar-text text-white" asp-action="Contact" asp-controller="Home">Contato</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link navbar-text text-white" asp-action="Registro" asp-controller="Usuarios">Registro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link navbar-text text-white" asp-action="Login" asp-controller="Usuarios">Login</a>
                        </li>

                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link navbar-text text-white" asp-action="Index" asp-controller="Usuarios">Meus dados</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link navbar-text text-white" asp-action="Index" asp-controller="Reclamacoes">Meus Incidentes</a>
                        </li>
                    }

                    @if (User.IsInRole("Administrador"))
                    {
                        <li class="nav-item">
                            <a class="nav-link navbar-text text-white" asp-action="Index" asp-controller="NiveisAcessos">Niveis de acesso</a>
                        </li>
                        
                    }
                </ul>

                <partial name="_LoginPartial" />

            </div>
        </div>
    </nav>

    <div class="container body-content">
        <div class="conteudoPrincipal ">
            @RenderBody()
        </div>

        <br />
        <br />

        <hr />

        <footer>
            <p>&copy; 2019 - CooperaCity</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.pt-BR.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.pt-BR.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

DenuncieSpam/Views/Shared/_ModalExclusao.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="modal" id="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Confirmar exclusão</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h4>Prosseguir com a exclusão de <b class="Nome"></b>?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-success btn-lg" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-outline-danger btn-lg btnExcluir">Excluir</button>
            </div>
        </div>
    </div>
</div>